### ISSUE TITLE
公式括号问题

### ISSUE THREAD

**Issue by tonyz0x0** [wind-liang/leetcode#1]
[这篇文章](https://github.com/wind-liang/leetcode/blob/master/leetCode-33-Search-in-Rotated-Sorted-Array.md)

> 此时 3 位置的数值对应为数组下标是 0 的值，1 位置的值对应数组下标是 5 的值。任意位置的对应规则是什么呢？0 -> 4, 1 - > 5，4 ->1，就是就是 （位置 + 偏移 % 数组的长度）。这里就是加上 4 模 7。

其中，`（位置 + 偏移 % 数组的长度）`应该改成`（位置 + 偏移）% 数组的长度`

**Comment by wind-liang** [comment]
谢谢，改过来了。
